### ISSUE TITLE
Give better error messages if user accidentally uses old psc version

### ISSUE THREAD

**Issue by codygman** [purescript-deprecated/grunt-init-purescript#6]
I was using psc 0.5.3 for some odd reason and got this:

```
~/programming/purescript/tutorials/purescript-by-example/new-project $ grunt
Running "clean:0" (clean) task

Running "clean:1" (clean) task

Running "pscMake:lib" (pscMake) task
>> Make failed:
>> "bower_components/purescript-arrays/src/Data/Array.purs" (line 486, column 3):
>> unexpected "\""
>> expecting "::"
Warning:  Use --force to continue.
```

I'm not sure if it's possible to provide a "try updating your psc to $version" error message in the case of pscMake:lib failing, or perhaps even checking before pscMake:lib, but it sure would be helpful.

Also not sure if it's much of a priority, but I got here from the purescript book and I'm sure you want new users experiences to be as seamless as possible. If you let me know how to do this I could try implementing something as well since I know you are very busy.

**Comment by garyb** [comment]
Thanks for the report. As well as the problem you're having this repository has fallen way behind where the current compiler is too. @paf31 is going to work on some updates for the book soon(ish) I believe, recommending people use [`pulp`](https://github.com/bodil/pulp) rather than building with Grunt. I've just updated the repository readme to direct users there in the meantime (hopefully they'll notice!).
